App/controllers/ingredient.py
from App.models import Ingredient
from App.database import db

#Controller for ingredients
def create_ingredient(name, quantity, user_id, image, unit):
    new_ingredient = Ingredient(name=name, quantity=quantity, user_id=user_id, image = image, unit = unit)
    db.session.add(new_ingredient)
    db.session.commit()
    return new_ingredient

def get_user_ingredient(id):
    return Ingredient.query.get(id)



def get_all_ingredients():
    return Ingredient.query.all()

def get_all_ingredients_json():
    ingredients = Ingredient.query.all()
    if not ingredients:
        return []
    return [ingredient.get_json() for ingredient in ingredients]

def get_ingredients_by_user(user_id, page, per_page, q, sort_by):
    query = Ingredient.query.filter_by(user_id=user_id)


    if q:
        search = f"%{q.lower()}%"
        query = query.filter(Ingredient.name.ilike(search))

  
    if sort_by == 'title_asc':
        query = query.order_by(Ingredient.name.asc())
    elif sort_by == 'title_desc':
        query = query.order_by(Ingredient.name.desc())
    elif sort_by == 'quantity_asc':
        query = query.order_by(Ingredient.quantity.asc())
    elif sort_by == 'quantity_desc':
        query = query.order_by(Ingredient.quantity.desc())
    elif sort_by == 'id_asc':
       query = query.order_by(Ingredient.id.asc())
    elif sort_by == 'id_desc':
        query = query.order_by(Ingredient.id.desc())
    else:
        query = query.order_by(Ingredient.name.asc())  
    return query.paginate(page=page, per_page=per_page)


def get_ingredients_by_user_json(user_id):
    ingredients = Ingredient.query.filter_by(user_id=user_id).all()
    return [ingredient.get_json() for ingredient in ingredients]

def update_user_ingredient(id, name, quantity, unit, image):
    ingredient = get_user_ingredient(id)
    if ingredient:
        if name:
            ingredient.name = name
        if quantity:
            ingredient.quantity = quantity
        if unit:
            ingredient.unit = unit
        if image:
            ingredient.image = image
        db.session.add(ingredient)
        db.session.commit()
        return ingredient
    return None

def delete_user_ingredient(id):
    ingredient = get_user_ingredient(id)
    if ingredient:
        db.session.delete(ingredient)
        db.session.commit()
        return True
    return False

App/controllers/missing_ingredients.py
from App.models import Recipe, Ingredient
from sqlalchemy.orm import joinedload

def get_recipes_missing_ingredients(user_id):
    user_ingredients = Ingredient.query.filter_by(user_id=user_id).all()
    user_stock = {ing.name.strip().lower(): ing.quantity for ing in user_ingredients}

    recipes_with_missing = []

    recipes = Recipe.query.options(joinedload(Recipe.ingredients)).all()

    for recipe in recipes:
        missing_ingredients = []

        for ri in recipe.ingredients:
            name = ri.name.strip().lower()
            required_qty = ri.quantity
            user_qty = user_stock.get(name, 0)
            if user_qty < required_qty:
                missing_ingredients.append({
                    'name': ri.name,
                    'required': required_qty,
                    'available': user_qty,
                    'unit': ri.unit,
                    'image': ri.image
                })

        if missing_ingredients:
            recipes_with_missing.append({
                'recipe': recipe,
                'missing_ingredients': missing_ingredients
            })

    return recipes_with_missing

App/controllers/user.py
from App.models import User
from App.database import db

def create_user(username, password):
    newuser = User(username=username, password=password)
    db.session.add(newuser)
    db.session.commit()
    return newuser

def get_user_by_username(username):
    return User.query.filter_by(username=username).first()

def get_user(id):
    return User.query.get(id)

def get_all_users():
    return User.query.all()

def get_all_users_json():
    users = User.query.all()
    if not users:
        return []
    users = [user.get_json() for user in users]
    return users

def update_user(id, username):
    user = get_user(id)
    if user:
        user.username = username
        db.session.add(user)
        return db.session.commit()
    return None
    

App/views/index.py
from flask import Blueprint, flash, redirect, render_template, request, send_from_directory, jsonify, url_for
from flask_jwt_extended import jwt_required, current_user
from App.controllers import *

index_views = Blueprint('index_views', __name__, template_folder='../templates')

@index_views.route('/', methods=['GET'])
@jwt_required(optional=True)
def index_page():
    user = current_user if current_user else None
    is_authenticated = user is not None

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')

    if user:
        paginated_recipes = get_recipes_by_user(user.id, page, 5, q, sort_by)
        recipes_json = [r.get_json() for r in paginated_recipes.items]
    else:
        paginated_recipes = []
        recipes_json = [""]

    return render_template(
        'index.html',
        current_user=user,
        is_authenticated=is_authenticated,
        recipes=paginated_recipes,
        recipes_json=recipes_json,
        q=q, sort_by=sort_by,
        num_ingredients=1
    )


@index_views.route('/init', methods=['GET'])
def init():
    initialize()
    return jsonify(message='db initialized!')


@index_views.route('/health', methods=['GET'])
def health_check():
    return jsonify({'status':'healthy'})


@index_views.route('/addRecipe', methods=['POST'])
@jwt_required()
def add_recipe():
    title = request.form.get('title')
    instructions = request.form.get('instructions')
    image = request.form.get('image') or ""
    user_id = current_user.id

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')

    if not title or not instructions:
        flash("Missing required fields", "error")
        return redirect(url_for('index_views.index_page', page=page, q=q, sort_by = sort_by))

    recipe = create_recipe(title, instructions, user_id, image)

    num_ingredients = int(request.form.get('num-ingredients') or 1)

    for i in range(num_ingredients):
        name = request.form.get(f'ingredient_name_{i}') or "none"
        quantity = request.form.get(f'ingredient_quantity_{i}') or "0"
        unit = request.form.get(f'ingredient_unit_{i}') or "none"
        img = request.form.get(f'ingredient_image_{i}') or "none"
        if name and quantity:
            add_ingredient_to_recipe(recipe.id, name, quantity, img, unit)
    
    flash("Recipe added", "success")
    return redirect(url_for('index_views.index_page', page=page, q=q, sort_by = sort_by))


#We gotta make sure this works first
@index_views.route('/updateRecipe/<int:id>', methods=['GET'])
@jwt_required()
def show_update_form(id):
    recipe = get_recipe(id)

    if not recipe or recipe.user_id != current_user.id:
        return redirect(url_for('index_views.index_page'))

    # Get page and search query from URL parameters
    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')


    # Fetch paginated recipe list for the current user
    paginated_recipes = get_recipes_by_user(current_user.id, page, 5, q, sort_by)
    recipes_json = [r.get_json() for r in paginated_recipes.items]

    return render_template(
        'index.html',
        current_user=current_user,
        is_authenticated=True,
        recipes=paginated_recipes,
        recipes_json=recipes_json,
        q=q,
        num_ingredients=len(get_ingredients_by_recipe(id)),
        ingredients_to_edit=get_ingredients_by_recipe(id),
        recipe_to_edit=recipe,
        sort_by = sort_by
    )


@index_views.route('/updateRecipe/<int:id>', methods=['POST'])
@jwt_required()
def update_recipe(id):
    recipe = get_recipe(id)

    page = int(request.form.get("page", 1))
    q = request.form.get("q", '')
    sort_by = request.args.get("sort_by", default='title_asc')

    if not recipe or recipe.user_id != current_user.id:
        return redirect(url_for('index_views.index_page'))

    # Update recipe title and instructions
    new_title = request.form.get('title')
    new_instructions = request.form.get('instructions')

    if not new_title or not new_instructions:
        return redirect(url_for('index_views.show_update_form', id=id, page = page, q=q, sort_by = sort_by))

    update_recipe_title(recipe.id, new_title)
    update_recipe_instructions(recipe.id, new_instructions)

    # Update ingredients
    ingredients = get_ingredients_by_recipe(recipe.id)

    for index, ingredient in enumerate(ingredients):
        name_key = f'ingredient_name_{index}'
        quantity_key = f'ingredient_quantity_{index}'
        image_key = f'ingredient_image_{index}'
        unit_key = f'ingredient_unit_{index}'

        new_name = request.form.get(name_key)
        new_quantity = request.form.get(quantity_key)
        new_image = request.form.get(image_key)
        new_unit = request.form.get(unit_key)

        if new_name:
            update_ingredient_name(ingredient.id, new_name)
        if new_quantity:
            update_ingredient_quantity(ingredient.id, new_quantity)
        if new_unit:
            update_ingredient_unit(ingredient.id, new_unit)
        if new_image is not None:
            update_ingredient_image(ingredient.id, new_image)

    flash("Recipe edited", "success")
    return redirect(url_for('index_views.index_page', page=page, q=q, sort_by = sort_by))


@index_views.route('/deleteRecipe/<int:id>', methods=['GET'])
@jwt_required()
def delete_user_recipe(id):
    recipe = get_recipe(id)

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", '')
    sort_by = request.args.get("sort_by", default='title_asc')
    
    if recipe and recipe.user_id == current_user.id:
        deleted = delete_recipe(id)
        if deleted:
            flash("Recipe deleted.", "success")
        else:
            flash("Recipe could not be deleted.", "error")
    else:
        flash("You are not authorized to delete this recipe.", "error")

    return redirect(url_for('index_views.index_page', page=page, q=q, sort_by = sort_by))

App/views/ingredient.py
from flask import Blueprint, flash, redirect, render_template, request, send_from_directory, jsonify, url_for

from flask_jwt_extended import jwt_required, current_user
ingredient_views = Blueprint('ingredient_views', __name__, template_folder='../templates')

from App.controllers import (
     get_ingredients_by_user, update_user_ingredient,
     create_ingredient,  get_user_ingredient,  delete_user_ingredient
)

@ingredient_views.route('/ingredient', methods=['GET'])
@jwt_required(optional=True)
def ingredient_page():
    user = current_user if current_user else None
    is_authenticated = user is not None

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')

    if user:
        paginated_ingredients = get_ingredients_by_user(user.id, page, 5, q, sort_by)
 
        ingredients_json = [i.get_json() for i in paginated_ingredients.items]
    else:

        paginated_ingredients = [""]
        ingredients_json = [""]

    return render_template(
        'ingredient.html',
        current_user=user,
        is_authenticated=is_authenticated,
        ingredients=paginated_ingredients,
        ingredients_json=ingredients_json,
        q=q,
        sort_by=sort_by,
        num_ingredients=len(ingredients_json)
    )


# route to add ingredient
@ingredient_views.route('/addingredient', methods=['POST'])
@jwt_required()
def add_ingredient():
    name = request.form.get('name')
    quantity = request.form.get('quantity')
    unit = request.form.get('unit')
    image = request.form.get('image') or ""
    user_id = current_user.id

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')

    if not name or not quantity or not unit:
        flash("Missing required fields", "error")
        return redirect(url_for('ingredient_views.ingredient_page', page=page, q=q, sort_by=sort_by))

    
    ingredient = create_ingredient(name=name, quantity=quantity, unit=unit, image=image, user_id=user_id)


    flash("Ingredient added", "success")
    return redirect(url_for('ingredient_views.ingredient_page', page=page, q=q, sort_by=sort_by))


@ingredient_views.route('/updateIngredient/<int:id>', methods=['GET'])
@jwt_required()
def show_ingredient_update_form(id):
    ingredient = get_user_ingredient(id)
    print("testing")
    if not ingredient or ingredient.user_id != current_user.id:
        return redirect(url_for('ingredient_views.ingredient_page'))

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')

    paginated_ingredients = get_ingredients_by_user(current_user.id, page, 5, q, sort_by)
    ingredients_json = [i.get_json() for i in paginated_ingredients.items]

    return render_template(
        'ingredient.html',
        current_user=current_user,
        is_authenticated=True,
        ingredients=paginated_ingredients,
        ingredients_json=ingredients_json,
        ingredient_to_edit=ingredient,
        q=q,
        sort_by=sort_by
    )


@ingredient_views.route('/updateIngredient/<int:id>', methods=['POST'])
@jwt_required()
def update_ingredient(id):
    ingredient = get_user_ingredient(id)

    page = int(request.form.get("page", 1))
    q = request.form.get("q", '')
    sort_by = request.form.get("sort_by", default='title_asc')

    if not ingredient or ingredient.user_id != current_user.id:
        return redirect(url_for('ingredient_views.ingredient_page'))

    new_name = request.form.get('name')
    new_quantity = request.form.get('quantity')
    new_unit = request.form.get('unit')
    new_image = request.form.get('image')
    update_user_ingredient(ingredient.id, new_name, new_quantity, new_unit, new_image)

    flash("Ingredient updated successfully", "success")
    return redirect(url_for('ingredient_views.ingredient_page', page=page, q=q, sort_by=sort_by))


@ingredient_views.route('/deleteIngredient/<int:id>', methods=['GET'])
@jwt_required()
def delete_ingredient_route(id):
    ingredient = get_user_ingredient(id)

    page = request.args.get("page", 1, type=int)
    q = request.args.get("q", '')
    sort_by = request.args.get("sort_by", default='title_asc')
  
    if ingredient is None:
        flash("Ingredient not found", "error")
        return redirect(url_for("ingredient_views.ingredient_page"))

    if ingredient.user_id == current_user.id:
        deleted = delete_user_ingredient(id)
        if deleted:
            flash("Ingredient deleted.", "success")
        else:
            flash("Ingredient could not be deleted.", "error")
    else:
        flash("You are not authorized to delete this ingredient.", "error")

    return redirect(url_for('ingredient_views.ingredient_page', page=page, q=q, sort_by=sort_by))

App/views/missing_ingredients.py
from flask import Blueprint, flash, redirect, render_template, request, send_from_directory, jsonify, url_for

from flask_jwt_extended import jwt_required, current_user
missing_ingredients_views = Blueprint('missing_ingredients_views', __name__, template_folder='../templates')

from App.controllers import (
    create_user, initialize, get_all_recipes, get_ingredients_by_user, update_user_ingredient,
    create_recipe, create_ingredient, delete_recipe, get_ingredient,
    add_ingredient_to_recipe, get_all_recipes_json, get_recipes_by_user,get_recipe,  get_ingredients_by_recipe,
     update_recipe_title,  update_recipe_instructions, delete_ingredient, update_ingredient_image, 
     update_ingredient_name, update_ingredient_quantity, get_user_ingredient,  delete_user_ingredient, get_recipes_missing_ingredients
   
  
)

@missing_ingredients_views.route('/missing_ingredients', methods=['GET'])
@jwt_required()
def missing_ingredients_page():
    user = current_user
    is_authenticated = user is not None
    q = request.args.get("q", default='', type=str)
    sort_by = request.args.get("sort_by", default='title_asc')

    all_missing = get_recipes_missing_ingredients(user.id)

    
    if q:
        all_missing = [entry for entry in all_missing if q.lower() in entry["recipe"].title.lower()]

    if sort_by == "title_asc":
        all_missing.sort(key=lambda x: x["recipe"].title.lower())
    elif sort_by == "title_desc":
        all_missing.sort(key=lambda x: x["recipe"].title.lower(), reverse=True)
    elif sort_by == "id_asc":
        all_missing.sort(key=lambda x: x["recipe"].id)
    elif sort_by == "id_desc":
        all_missing.sort(key=lambda x: x["recipe"].id, reverse=True)

    return render_template(
        "missing_ingredients.html",
        current_user=user,
        is_authenticated=is_authenticated,
        recipes=all_missing,
        q=q,
        sort_by=sort_by,
        num_recipes=len(all_missing)
    )

App/templates/401.html
{% extends "layout.html" %}
{% block title %}Not Authorized{% endblock %}
{% block page %}Not Auhtorized{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <div class="card-content">
                <h1>401 - Not Authorized</h1>
                <p>You do not have permission to access this resource. Please check your credentials and try again.</p>
                <p>{{error}}</p>
            </div>
            <div class="card-action">
                <a href="/" class="waves-effect waves-light btn">Go Home</a>
                <a href="javascript:history.back()" class="waves-effect waves-light btn">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/ingredient.html
{% extends "layout.html" %}
{% block title %}WE GO COOK{% endblock %}
{% block page %}WE GO COOK{% endblock %}

{% block content %}
<li>
    <form method="GET" action="{{ url_for('ingredient_views.ingredient_page') }}" class="search-form">
        <input type="search" name="q" placeholder="Search Ingredients" value="{{ q }}" />
        <button type="submit" class="search-bar"><i class="bi bi-search"></i></button>
    </form>
</li>  

{% if is_authenticated %}
<input type="checkbox" id="recipe-toggle">
<label for="recipe-toggle" class="toggle-label">➕ Add New Ingredient</label>

<aside class="slide-in-form">
  <form method="POST" action="{{ url_for('ingredient_views.add_ingredient') }}">
    <div class="form-field">
      <label for="name">Name</label>
      <input name="name" id="name" required>
    </div>

    <div class="form-field">
      <label for="quantity">Quantity</label>
      <input name="quantity" id="quantity" type="number" min="0" step="any" required>
    </div>

    <div class="form-field">
      <label for="unit">Unit</label>
      <input name="unit" id="unit" placeholder="e.g. grams, ml, cups" required>
    </div>

    <div class="form-field">
      <label for="image">Image URL</label>
      <input name="image" id="image">
    </div>

    <div style="margin-top: 20px;">
      <button type="submit" class="recipe-btn">💾 Add Ingredient</button>
      <label for="recipe-toggle" class="recipe-btn" style="background-color: #EC5228; cursor: pointer;">Cancel</label>
    </div>
  </form>
</aside>


<form method="get" action="{{ url_for('ingredient_views.ingredient_page') }}" style="display: block; visibility: visible; opacity: 1; z-index: 999;">
    <p style="color: white;">
      <strong>Sort Ingredients:</strong>
      <select class= "sort-recipes-select" name="sort_by" onchange="this.form.submit()" style="border-color: #EC5228; display: inline-block; background: rgba(255, 178, 0, 0.6); color: black; z-index: 999;">
        <option value="id_asc" {% if sort_by == 'id_asc' %}selected{% endif %}>ID ↑(asc)</option>
        <option value="id_desc" {% if sort_by == 'id_desc' %}selected{% endif %}>ID ↓(desc)</option>
        <option value="title_asc" {% if sort_by == 'title_asc' %}selected{% endif %}>Name A–Z</option>
        <option value="title_desc" {% if sort_by == 'title_desc' %}selected{% endif %}>Name Z–A</option>
        <option value="quantity_asc" {% if sort_by == 'quantity_asc' %}selected{% endif %}>Quantity ↑(asc)</option>
        <option value="quantity_desc" {% if sort_by == 'quantity_desc' %}selected{% endif %}>Quantity ↓(desc)</option>
      </select>
      <input type="hidden" name="q" value="{{ q }}">
    </p>
</form>




{% if ingredients.items|length == 0 %}
  <p style="color: #D91656; font-weight: bold;">You have no ingredients saved yet.</p>
{% else %}
<h1 class ="inventory-header" style="color: #d97b16d7; font-weight: bold;  ">Ingredients Stock</h1>
<div class="ingredient-container">
    {% for ingredient in ingredients.items %}
      <div class="ingredient-card">
        <!-- Ingredient Image -->
        {% if ingredient.image%}
          <img src="{{ ingredient.image }}" alt="{{ ingredient.name }} image" class="ingredient-img">
        {% else %}
          <img src="https://img.freepik.com/free-photo/fresh-vegetables-colorful-pasta-with-mushroom-garlic-pepper-white-surface_176474-312.jpg?t=st=1745179842~exp=1745183442~hmac=a3cbf1f05236fff3910f2174d3e6c2e53478941ad2ebf0d84500872e6e22e32e&w=1380" alt="Default image" class="ingredient-img">
        {% endif %}
  
        <h3>{{ ingredient.name }}</h3>
        <p>ID: {{ ingredient.id }}</p>
        <p>Quantity: {{ ingredient.quantity }} {{ ingredient.unit }}</p>
        
        <div class="button-container">
          <form method="GET" action="{{ url_for('ingredient_views.show_ingredient_update_form', id=ingredient.id) }}">
            <input type="hidden" name="page" value="{{ ingredients.page }}">
            <input type="hidden" name="q" value="{{ q }}">
            <input type="hidden" name="sort_by" value="{{ sort_by }}">
            <button class="recipe-btn" type="submit">✏️ Edit/View Ingredient</button>
          </form>
  
          <form method="GET" action="{{ url_for('ingredient_views.delete_ingredient_route', id=ingredient.id) }}">
            <input type="hidden" name="page" value="{{ ingredients.page }}">
            <input type="hidden" name="q" value="{{ q }}">
            <input type="hidden" name="sort_by" value="{{ sort_by }}">
            <button class="recipe-btn" type="submit">🗑 Delete Ingredient</button>
          </form>
        </div>
      </div>
    {% endfor %}
  </div>
  
  
{% endif %}


<div class="pagination">
    <ul>
      {% if ingredients.has_prev %}
        <li><a class="pagination-link" href="{{ url_for('ingredient_views.ingredient_page', page=ingredients.prev_num, q=q, sort_by=sort_by) }}"><i class="bi bi-arrow-left"></i></a></li>
      {% else %}
        <li><span class="pagination-link disabled"><i class="bi bi-arrow-left"></i></span></li>
      {% endif %}

      {% for page_num in ingredients.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
        {% if page_num %}
          {% if ingredients.page == page_num %}
            <li><span class="pagination-link active-page">{{ page_num }}</span></li>
          {% else %}
            <li><a class="pagination-link" href="{{ url_for('ingredient_views.ingredient_page', page=page_num, q=q, sort_by=sort_by) }}">{{ page_num }}</a></li>
          {% endif %}
        {% else %}
          <li><span class="pagination-link disabled">…</span></li>
        {% endif %}
      {% endfor %}

      {% if ingredients.has_next %}
        <li><a class="pagination-link" href="{{ url_for('ingredient_views.ingredient_page', page=ingredients.next_num, q=q, sort_by=sort_by) }}"><i class="bi bi-arrow-right"></i></a></li>
      {% else %}
        <li><span class="pagination-link disabled"><i class="bi bi-arrow-right"></i></span></li>
      {% endif %}
    </ul>
  </div>
  {% else %}
  <div class="meme-container">
    <div class="meme-card">
      <img src="https://media.makeameme.org/created/why-is-there-7e933763f7.jpg" alt="Why is there" />
    </div>
  </div>

  {% endif %}
  {% if ingredient_to_edit %}
  <aside class="recipe-aside" style="display: block;">
    <form method="POST" action="{{ url_for('ingredient_views.update_ingredient', id=ingredient_to_edit.id) }}">
        <input type="hidden" name="page" value="{{ ingredients.page }}">
        <input type="hidden" name="q" value="{{ q }}">

        <div class="form-field">
          <label>Name</label>
          <input type="text" name="name" value="{{ ingredient_to_edit.name }}" required>
        </div>

        <div class="form-field">
          <label>Quantity</label>
          <input type="text" name="quantity" value="{{ ingredient_to_edit.quantity }}" required>
        </div>

        <div class="form-field">
          <label>Unit</label>
          <textarea name="unit" rows="6" required>{{ ingredient_to_edit.unit}}</textarea>
        </div>

        
         <div class="form-field">
            <label for="image">Image URL</label>
            <input name="image" id="image">
         </div>

        <div class="form-field" style="margin-top: 20px;">
          <button type="submit" class="recipe-btn">💾 Save Changes</button>
          <a href="{{ url_for('ingredient_views.ingredient_page', page=ingredients.page, q=q, sort_by=sort_by) }}" class="recipe-btn" style="background-color: #EC5228;">Cancel</a>
        </div>
    </form>

    
  </aside>
{% endif %}

{% endblock %}

App/templates/message.html
{% extends "layout.html" %}
{% block title %}{{title}}{% endblock %}
{% block page %}{{title}}{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <p>{{message}}</p>
        </div>
    </div>
</div>
{% endblock %}

App/templates/missing_ingredients.html
{% extends "layout.html" %}
{% block title %}WE GO COOK{% endblock %}
{% block page %}WE GO COOK{% endblock %}

{% block content %}
<li>
  <form method="GET" action="{{ url_for('missing_ingredients_views.missing_ingredients_page') }}" class="search-form">
      <input type="search" name="q" placeholder="Search Recipes" value="{{ q }}" />
      <button type="submit" class="search-bar"><i class="bi bi-search"></i></button>
  </form>
</li>  

{% if is_authenticated %}


<form method="get" action="{{ url_for('missing_ingredients_views.missing_ingredients_page') }}" style="display: block; visibility: visible; opacity: 1; z-index: 999;">
  <p style="color: white;">
    <strong>Sort Ingredients:</strong>
    <select class= "sort-recipes-select" name="sort_by" onchange="this.form.submit()" style="border-color: #EC5228; display: inline-block; background: rgba(255, 178, 0, 0.6); color: black; z-index: 999;">
      <option value="id_asc" {% if sort_by == 'id_asc' %}selected{% endif %}>ID ↑(asc)</option>
      <option value="id_desc" {% if sort_by == 'id_desc' %}selected{% endif %}>ID ↓(desc)</option>
      <option value="title_asc" {% if sort_by == 'title_asc' %}selected{% endif %}>Name A–Z</option>
      <option value="title_desc" {% if sort_by == 'title_desc' %}selected{% endif %}>Name Z–A</option>
    </select>
    <input type="hidden" name="q" value="{{ q }}">
  </p>
</form>

{% if recipes|length == 0 %}
  <p style="color: #D91656; font-weight: bold;">You're not missing ingredients for any recipes! 😊</p>
{% else %}
  <h1 class="inventory-header" style="color: #d97b16d7; font-weight: bold;">Recipes You're Missing Ingredients For ({{ num_recipes }})</h1>
  <div class="recipe-container">
    {% for entry in recipes %}
      <div class="ingredient-card">
        <h3>{{ entry.recipe.title }}</h3>
        {% if entry.recipe.image %}
          <img src="{{ entry.recipe.image }}" alt="{{ entry.recipe.title }} image" class="ingredient-img">
        {% endif %}

        <h4 style="color: #EC5228;">Missing Ingredients:</h4>
        <ul>
          {% for item in entry.missing_ingredients %}
            <li>
              <strong>{{ item.name }}</strong> — You have {{ item.available }} / Need {{ item.required }} {{ item.unit }}

            </li>
          {% endfor %}
        </ul>
      </div>
    {% endfor %}
  </div>
{% endif %}


{% else %}
<div class="meme-container">
  <div class="meme-card">
    <img src="https://media.makeameme.org/created/why-is-there-7e933763f7.jpg" alt="Why is there" />
  </div>
</div>
{% endif %}
{% endblock %}